### ISSUE TITLE
Look for .env variables when running Lambdas

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#167]
Use this, or an approach similar to this:
https://github.com/motdotla/dotenv

**Comment by hakanson** [comment]
I was also thinking about this, because I have been using code like this which keeps secrets and dependencies out of the code.
```
var appId = process.env.AMAZON_APP_ID || '';
var bstId = process.env.BST_SECRET_KEY;
var dynamoDBTableName = process.env.MY_DYNAMODB_TABLE;

exports.handler = bst.Logless.capture(bstId, function (event, context) {
    var alexa = Alexa.handler(event, context);
    alexa.appId = appId;
    alexa.dynamoDBTableName = dynamoDBTableName;
    alexa.registerHandlers(handlers);
    alexa.execute();
});
```

I wondered if `bst` should include a command line option like `docker run` does with `--env-file` to  "Read in a file of environment variables"

I decided that for me, the easier option was to make `#!/bin/bash` the first line so I can just `source .env` before I run `bst proxy lambda index.js` as it felt a little too coupled otherwise.

Here is an example `.env` which both includes those "secrets" and some AWS configuration (like the specific IAM profile I want to use).
```
#!/bin/bash
AWS_PROFILE=MySkillDeveloper
AWS_REGION=us-east-1
AMAZON_APP_ID=amzn1.ask.skill.00000000-1111-2222-3333-444444444444
BST_SECRET_KEY=00000000-1111-2222-3333-444444444444
MY_DYNAMODB_TABLE=MySkillTable

```
 Note,

**Comment by jkelvie** [comment]
Closed as we do not plan to implement near-term
