### ISSUE TITLE
bst proxy lambda console is showing computer activity

### ISSUE THREAD

**Issue by ekt1701** [bespoken/bst#180]
I was using bst proxy lambda to test an Alexa Nodejs skill.   However, the terminal window is also displaying general internet activity.

For example:

INFO  2017-01-02T02:15:34.840Z FS.Watch Event: rename. File: Library/Application Support/Firefox/Profiles/mza4pid3.default-1477005639201/prefs.js. Reloading.

or 

INFO  2017-01-02T02:16:15.626Z FS.Watch Event: change. File: Library/Google. Reloading.

It is a constant stream of INFO activity unrelated to the Alexa Skill.

I haven't used bst proxy lambda in a while, but I don't recall seeing this activity before.
I am on OS X El Capitan BST: v0.9.25 node: v4.6.0

**Comment by jkelvie** [comment]
Hi @ekt1701, where is the lambda installed that this is happening? And how are you calling it?

We look for any changes to files in the directory where the lambda is run from, as well as its sub-directories. So perhaps there is a symbolic link pointing back to root in the lambda directory? Trying to think how this could happen.

**Comment by ekt1701** [comment]
@ jkelvie Here is the command I am using:  `bst proxy lambda /Users/EKT2014/Desktop/alexa-google-search-master/src/index.js`

Right after I get the URL for the skill configuration, the internet activity starts being displayed in the terminal.  It keeps going until I terminate it.

**Comment by jkelvie** [comment]
Okay, I understand. So to prevent this from happening, do a:
`cd /Users/EKT2014/Desktop/alexa-google-search-master/`
And run bst proxy from there as:
`bst proxy lambda src/index.js`

It is happening because you are running bst from the root level of your filesystem. It assumes anything in its current directory or below is part of the Lambda project.

I am going to leave this issue open for now to see if there is a better way we can handle this.

**Comment by ekt1701** [comment]
Thanks, that fixed the issue. Now that you mention it, previously, I would cd to the directory, then run bst proxy.  But I forgot that step, since I mostly use bstpy.  

BTW, have you tried the google search skill?  It works well.
