### ISSUE TITLE
Refactor/remove commander module from bin classes

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#238]
Instead, we should have our own abstraction that is extremely testable.

It should be easily configurable (setting options, like with commander), but also have its own error and standard output that it collects. 

That output will then be easily testable (i.e., we don't have to do all sorts of weird things to try mock the standard out)

**Comment by tjbenton** [comment]
[nixt](https://github.com/vesln/nixt) will allow you to test any cli tool, there's no need to create your own home grown cli manager. I've used it to test several apps that I used [commander](https://www.npmjs.com/package/commander), or [caporal](https://www.npmjs.com/package/caporal). There's no need to mock anything because it makes testing a cli app extremely simple. 


Here's an example from one of my apps that use it. This app is using `ava` for testing but `nixt` works with any testing lib. Just make sure the tests are running serially. 

```js
import ava from 'ava-spec'
const test = ava.group('CLI:')
import nixt from 'nixt'
import path from 'path'
const cli = nixt().base('../../../bin/project ')
const test_root = path.join(__dirname, 'cli-fixtures')
test.serial.group('server', (test) => {
  const root = path.join(test_root, 'cli-server-test')
  const base = cli.clone().cwd(root) // sets the cwd to the `test/fixtures/cli-fixtures/cli-server-test` folder

  test.cb('status - not running', (t) => {
    base.clone() 
      .run('status') // same as running `project status` 
      .stdout(/server is not running/)
      .end(t.end)
  })

  test.cb('stop - isn\'t running', (t) => {
    base.clone() 
      .run('stop') // same as running `project stop`
      .stdout(/server isn't running/)
      .end(t.end)
  })

  test.cb('start - was started', (t) => {
    base.clone() 
      .run('start') // same as running `project start`
      .stdout(/server was started http:\/\/localhost/)
      .end(t.end)
  })

  test.cb('start - is already running', (t) => {
    base.clone() 
      .run('start') // same as running `project start`
      .stdout(/server is already running/)
      .end(t.end)
  })

  test.cb('status - is running', (t) => {
    base.clone() 
      .run('status') // same as running `project status`
      .stdout(/server is running/)
      .end(t.end)
  })
})
```


Hope this helps out with your testing

**Comment by jkelvie** [comment]
Hi @tjbenton - that is very useful, thanks for bringing that to our attention. I really like the functionality of commander, but we have really struggled with unit-testing it. This may be exactly what we need.
