### ISSUE TITLE
Add support for proxying GET requests and other HTTP methods to proxy

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#253]
The proxy should support HTTP methods other than just POST (which is all it currently supports).

We do need to make sure in changing it the health check pings still work - they currently rely on a GET call simply returning ALIVE.

One possible solution is to make sure in the case of no node-id being supplied that it returns a 200 code, though still with a clear message. Alternatively, we could add a special path for pings like "proxy.bespoken.tools/ping".

**Comment by jkelvie** [comment]
Request by @NovaGL for use with testing Flash Briefings.

**Comment by NovaGL** [comment]
Have you made any progress on this?

**Comment by jkelvie** [comment]
No, but it is coming up shortly on the roadmap. We will let you know once it is done! Thanks for checking in with us about it @NovaGL

**Comment by jperata** [comment]
@NovaGL 
We added the changes for the extra http methods and you can have an sneak peek to them.

You will have to update the bst tool:
`npm install --global bespoken-tools@1.0.3`

And the proxy lambda should point to our dev server, so the command in terminal should looks like:
`bst proxy lambda index.js --bstHost proxy-dev.bespoken.tools --bstPort 5000`

your proxy url since it's pointing to dev will be: 
https://proxy-dev.bespoken.tools/?node-id=<secretKey>

where secretKey is the uuid at the end of the line in the console output
Your URL for viewing skill data:
https://bespoken.tools/dashboard?id=<proxy_name>&key=<uuid_secret_key>

**Comment by NovaGL** [comment]
Thanks for that. I found a feed but the url was unique so couldn't figure out how to change it for day to day.

If I find something I want to test will let you know.

How does BST know whether its a POST or a GET

**Comment by jperata** [comment]
with this version we just pass around whatever http request pass to the proxy, so the http request will get with it's own method

**Comment by NovaGL** [comment]
Thanks. Your tool is very useful.

I have to figure out how to get Google Assistant on phones to work with it too. So many things so little time

**Comment by NovaGL** [comment]
@jperata I found the feed I want
https://rss.whooshkaa.com/rss/podcast/id/1820

The only problem is the actual audio of it is not on HTTPS. Anything I can do to make it work on Alexa?

**Comment by jkelvie** [comment]
H @novagl, if you take the audio URLs that are returned and change them
from HTTP to HTTPS, that will work. You do need some code modify the XML
payload though.

-John

**Comment by NovaGL** [comment]
Did that and it worked, this why I removed the message. I haven't tried the GET method yet, if I have something that needs it I will let you know.

**Comment by jkelvie** [comment]
Closed with #321
