### ISSUE TITLE
test PlaybackController.NextCommandIssued

### ISSUE THREAD

**Issue by giusepped** [bespoken/bst#456]
I am trying to test `PlaybackController.NextCommandIssued` when tapping the next button on an Echo Spot/Show but cannot find a way to do that.

Am I missing something or is it something that you're looking into by any chance?

Thanks!

**Comment by jperata** [comment]
if you are currently using the bst commands, 
testing with bst utter next, will work as long as it's a sample utterance present in your model for that specific intent.

You can use bst intend PlaybackController.NextCommandIssued to generate a json with that specific 
intent too.

If you are trying to write unit tests instead, we recommend you to check https://github.com/bespoken/virtual-alexa
It's our most update library for unit testing, and it also support doing intents that way.

**Comment by jperata** [comment]
Sorry,  < PlaybackController.NextCommandIssued > is an specific request type, for that kind of tests then, virtual-alexa would be specially useful, you can still use our utter command in there, but you can add a filter so that you can manipulate the request into including that specific type.
Here is a basic example:

https://github.com/bespoken/virtual-alexa#using-the-request-filter

**Comment by jkelvie** [comment]
I have added an issue for this on virtual alexa - this will allow for these calls to be made in programmatic tests. We do not have plans to support this on the command-line though near-term.
