### ISSUE TITLE
Research: How to secure the BST stats endpoint.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#478]
Currently, the endpoint where we write the BST stats is easily reachable. Research on how to secure it so that no false information is posted to it. Document the findings so that we can implement it before the official release of BST 2.0.

**Comment by jperata** [comment]
**Expanded reasons on why to secure bst-stats**
-  It's an endpoint that can feed data on our database, causing increased costs and false data if someone use it maliciously.

**Difficulties on securing bst-stats**
- Bst is open source and in javascript so any "tricky" thing we may do in order to hide how that code is setup in order to provide security will be exposed. 
- Since it's a CLI client, environment variables that we can setup during deployment similar to what we do with other endpoints is not possible to do in a hidden way.
- Different available versions means that enabling security now that the stats are currently present will prevent any older version to register stats for the client side.

**Possible solutions for enabling security**
Due the difficulties to enable a client and endpoint conjoined form of security, the main efforts need to be centered server side.

a) Calls to the endpoint from a source different than bst-server ip can be throttled (we can use something like [this](https://github.com/jhurliman/node-rate-limiter), in order to limit the risk of DDOS attacks, that can flood our data.
b) Calls to the endpoint can have the payloads validated to match the exact structure of the corresponding command to avoid getting trash data.
c) One way to try to improve the security would be that since the nodeId is sent along the stats, we can verify if that is nodeId exists, before registering the data. (bst stats is called without expecting it's response so extra delays don't affect bst performance). While this helps a little with security at the end if someone wants to really mess with the data getting a valid nodeId is a trivial thing to do.
 
Neither of this avoid someone actively trying to write malicious logs, so we can chose if we want to take any of this approaches and apply then progressively.

**Comment by matedeilo** [comment]
Hi guys, I suggest to limit the request dynamically by some attribute or even limit the users on same ip. Like this [limiter](https://github.com/ded/express-limiter).
Example:
```
limiter({
  path: '/api/action',
  method: 'get',
  lookup: ['request.attribute'], //maybe some property who identifies the user.
  // 150 requests per hour
  total: 150
})
```

**Comment by dmarvp** [comment]
Thanks @jperata for such a well-done research. Based on what we have I think your proposed solutions "a" and "c" are the best ones to implement. I don't think they are high priority but we could do it on the following sprint. @jkelvie any thoughts?

**Comment by jperata** [comment]
The research was completed and we haven't had any security issue in 2 years. Closing the issue
