### ISSUE TITLE
All options for bst speak command are not shown

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#484]
### Description:
For the `bst speak` command, the locale and voiceID options are not listed when typing help.

Additionally, when running the speak command before setting the token, an error is shown when specifying the locale option.

### Environment:
- Version: 2.0.10
- OS: Windows 10
- Node version: 8.11.3

### Steps To Reproduce
1. Run bst speak
2. See that the options for locale and voiceID are not listed

### Expected behavior
I expected to see the options listed.

### Actual behavior
I did not see the options listed.

Screenshot attached.
![screenshot 13](https://user-images.githubusercontent.com/17267/44668297-9c9c6b80-a9e2-11e8-8ad2-ff949bdb0e1f.png)

**Comment by ecruzado** [comment]
blocked until release a new version

**Comment by jperata** [comment]
This is verified to work for bst speak -h and bst speak --help , but should work also when bst speak is called with no parameters, at the moment it set's an incomplete help (because the validation is made before adding the extra options), and it tries to evaluates the message parameter even if it's empty sending an error message 

<img width="1674" alt="screen shot 2018-09-10 at 3 06 10 pm" src="https://user-images.githubusercontent.com/8781604/45321479-15371800-b50b-11e8-97b4-5ce9c44205d2.png">

**Comment by jperata** [comment]
Marked as verified
build = bespoken-tools@2.0.23
