### ISSUE TITLE
BST 2.0 first set of tip messages.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#493]
Regarding #357 and from a recent email:

> We have to define the “tips” messages that we’ll store in our database. @GitBoHub  is going to help us with the phrasing, but first we need to come up with a small set of tips based on the features we already have (I’m thinking at least 10 to start?). 
>
> Examples can be:
> 
>- Pro tip!: Use bst launch to…
>- With bst utter you can…
>- Did you know? You can use the same YAML syntax for both your end to end and unit tests. Find out more at read.bespoken.io
>- Here’s a tip💡: …
>
> BTW, Is the output in unicode? That way we could include things like the little lightbulb (just thinking out loud here, it’s not a requirement). Anyway, once we have this initial set of tips we can hand it to @GitBoHub  so she can review them and make any adjustments needed.
> 
> Finally, could you try and come up with an ideal message length based on how it’s seen in the output? To me, we should try to keep it in one line or two at most. But I’m sure that default line sizes may vary between Windows and OSX so we have to take that into account as well.

**Comment by jperata** [comment]
10 starting tips, once this are approved I'll set them in our firebase database for bst to grab

- Use bst launch to simulate someone opening your skill.
- With bst utter you can interact with your skill and we'll handle your intents for you
- Did you know? You can use the same YAML syntax for both your end to end and unit tests. Find out more at https://read.bespoken.io
- Pro tip!: Each of our tools has lots of elements that you can customize like the userId or the locale, find about them by using your favorite bespoken-tool and the --help option
- You can use bst speak to interact with Alexa directly!
- Here is a tip! Use the -u option if you want to use our tools with a custom url instead of a our local bst proxy.
- Did you know? bst proxy not only works for Alexa, you can use bst proxy function to start a proxy to a google cloud function.
- Have some doubts?, https://read.bespoken.io is the place to go for full documentation on our tools
- bst test allows you to have a complete set of unit tests using a simple YAML format. Find more at https://read.bespoken.io
- Remember you can contact us at https://gitter.im/bespoken/bst

**Comment by jkelvie** [comment]
Looks good - though it should say "Have questions?" not "have some doubts?,"

**Comment by jperata** [comment]
Windows is the most limited console talking about the characters allowed, the default in a big resolution screen es 130 characters per line (this doesn't take the prompt in consideration but our tips always appear on a new line). So the maximum length we should use is about 260 characters.
