### ISSUE TITLE
Add the ability to filter which tests should be run by tag

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#501]
**Is your feature request related to a problem? Please describe.**
For certain executions of bst test, it would be useful if only certain tests were run.

The main use-case is to only run tests based on a platform parameter, but a more broad capability would be to add generic tags to the tests, and to the filter which tests are run by tag.

Overall, the goal is to allow for creating a single, unified set of tests that work across platforms and use-cases, but allows for some tests to still be included that only work for certain platforms or scenarios.

**Describe the solution you'd like**

It could be like this:
```
---
- test: My test that only works for Alexa
- tags: alexa
- MyAlexaOnlyIntent:
  - response.outputSpeech.ssml: Result
````

When running the test, one would specify the test command with a new optional tag parameter:
```
bst test --tag alexa
```

**Describe alternatives you've considered**
Alternatively, there could be simply a platform parameter added to the test. However, this seems less useful than the more general tagging capability. Tags, though generic, are still easy to work with and understand.

**Additional context**
This was requested by an important customer.

**Comment by MKen-li** [comment]
This feature is very similar of what grouping is for automation testing, in Nunit is called Categories and in TestNg is called Groups. We might want to be aligned to this already existing features.

Another way that I could see this working would be.

1. Change the name from tag to group
---
- test: My test that only works for Alexa
- groups: alexa
- MyAlexaOnlyIntent:
  - response.outputSpeech.ssml: Result

2. Execution: one way would be to simply do: bst test --groups alexa and that would be enough but we need to considered that when a skill or action have several hundred or thousand test cases we probably need to have a more complete structure of execution. For this we could have some attributes in the  testing.json to indicate what test are suppose to be included or excluded in the Run.

"groups"{
  "run" {
    "include" : "sanity, regression",
    "exclude": "broken"		
  }
}
In this case all the test that have the sanity or regression  tag would be run by default and the ones that are from the broken group will not. For example a test that is from sanity and broken won't be executed.

We could also go one step further in the future and have groups of groups

"groups"{
    "define: "alexa"{
      "include": "CardTest",
      "include": "nonCardTest"
      "exclude": "broken".
    }  
    "define: "regression"{
      "include": "alexa",
      "include": "google",
      "exclude": "cortana".
    }
  
    "run"{
      "include": "regression"
    }
}

This example shows that the alexa group is inside the regression group and finally we run what is inside the regression group. Seems a bit complicated at the beginning but the point is to be able to run a particular set of test on the fly instead of running all the test cases every time.

This way we would have a default run test execution that can be change updating the testing.json or overwritten in the call

bst test --groups alexa,google
bst test --include CardTest
bst test --exclude broken 

@jkelvie

**Comment by jperata** [comment]
Released on latest beta
Usage (both in testing.json and overwriting parameters)
  --include <tags to include separated by commas>
  --exclude <tags to include separated by commas>

if something fits inclusion and exclusion the exclusion will take priority

**Comment by MKen-li** [comment]
Marked as bloked, waiting for:
https://github.com/bespoken/bst/issues/518
https://github.com/bespoken/bst/issues/519

**Comment by jperata** [comment]
Unblocked on alpha (2.0.35)

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.0.33
