### ISSUE TITLE
Make unit-tests with bst easy to use with a debugger

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#508]
**Is your feature request related to a problem? Please describe.**
Right now, it is difficult to use a debugger with our tools because they spawn new processes. This is because `bst test` creates a new process, and our unit-tests are set to `runInBand=false` by default.

**Describe the solution you'd like**
bst-test should be its own binary akin to bst and bst-server. Since it does not spawn its own process, it allows for debugging unit-tests using our tools. This is different from calling `bst test`, which does spawn a new process, and therefore cannot be easily used with a debugger.

Additionally, runInBand in skill-testing-ml should be made a top-level property of the `testing.json` file.  The file might look like this:  
```
{
   "type": "unit",
   "runInBand": false,
   "jest": {
   }
} 
```
It should default to true, and should set the value here:
https://github.com/bespoken/skill-testing-ml/blob/master/lib/runner/CLI.js#L43

Note, for end-to-end testing, this should still always be forced to false. That is because runInBand forces Jest to run in the current process and not spawn new ones. This should be our default behavior, but for unit tests, we want to allow for people to set it false (allowing for parallelized tests).

**Comment by jperata** [comment]
Run bst test on an old version of bst with a task monitor enabled for unit tests (like the default guess the price), you will see multiple node process being triggered.
With the latest changes running 
bst-test (not bst test)
 without any parameters should show only one node process.

To enable multiprocessing again add runInBand as a parameter or in the testing.json with value set to false. 

This functionality only allows enabling it on unit tests for e2e it will always do only one process.

**Comment by MKen-li** [comment]
Moving back to dev

**Comment by jperata** [comment]
The reason why this was moved back to dev was due the trace logs not being present while the runInBand value is set to false (parallel running the tests), this seems to be an issue with jest. 
https://github.com/facebook/jest/issues/2441

The output that jest prints out and overwrite of the running tests keeps overwriting the logs, a workaround  is setting the jest.verbose property to false (since then jest don't overwrite anything as it is not printing nothing jest related, and our trace are their own logs). The aftereffect of that is sadly that our logs printout without color. And in the process missing the coverage and test status.

Since having the console output  for trace not being so useful if there are several running tests in parallel, i believe that we can wait until jest itself include a fix, specially since now runInBand = true is our default behavior.

**Comment by dmarvp** [comment]
@MKen-li @jkelvie after reviewing this issue with @jperata I believe that it's ok for us to not show the trace if running tests in parallel, as we would be showing requests and responses from different tests mixed up. We should make the trace functionality only available for running tests sequentially.

**Comment by MKen-li** [comment]
Marked as verified
Build bespoken-tools@2.0.29
