### ISSUE TITLE
Include client on virtual device calls

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bst#584]
### Description:
related to https://github.com/bespoken/virtual-device-sdk/issues/121
and https://github.com/bespoken/skill-testing-ml/issues/233

Once those issues are implemented, we need to set the parameter "client" to "cli" on each call made from this project either by the sdk or the skill-testing-ml libraries.

### Expected behavior
After doing this, the virtual device stats will have a new property in them "client" which will specify "cli" in their value.

### Actual behavior
We don't know which client is calling the virtual-device endpoints.

**Comment by jperata** [comment]
Can be tested on the latest beta of bst (2.3.20)
in order to test, set the virtual device env variable to point to dev
1) run:
bst speak hello world
check on mongo the virtualdevicestats table for the used token and the stats should include the client as cli

2) run an e2e test
the records saved should also include cli as the client saved

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@beta
