### ISSUE TITLE
Add Proxy functionality

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bst#602]
**Is your feature request related to a problem? Please describe.**
A user that has proxy restrictions  can't use the bst tools

**Describe the solution you'd like**
Two new properties on the testing.json file:
proxyURL = String value that will receive the URL of the proxy 
proxyEnabled = A boolean value that will be set to false as default
@jperata 

**Additional context**
None.

**Comment by jkelvie** [comment]
I would suggest we use something like this to do it:
https://www.npmjs.com/package/https-proxy-agent

We can test using this proxy service:
https://www.proxysite.com/

And I would use the environment variable HTTPS_PROXY rather than setting something in testing.json. That environment variable is the universal standard for setting an HTTP proxy. It just so happens that node, in its infinite wisdom, does not support it.

**Comment by jperata** [comment]
I have tried using the Global Protect VPN Client software, which is the one used by our client. But it won't work without a proper portal and credentials, and the free proxies don't allow for something like that. Using other VPN software like tunnel bear or OpenVpn doesn't reproduce the issue that is shown for the client,  using our tool inside the VPN solutions work. 

I will continue by working with just the proxy elements as described initially.

**Comment by jkelvie** [comment]
I don't understand why we are discussing VPNs. Can you explain what the Mercedes VPN has to do with testing a proxy?

There is no reason at all to expect a VPN to reproduce the behavior. It is completely different from a Proxy.

*John Kelvie*

Co-Founder & CEO | 202-251-7107

Bespoken ( https://bespoken.io/ ) - Testing, Tuning and Monitoring for Voice.

**Comment by jperata** [comment]
It can be tested on the latest Beta ( 2.4.58) , for testing set the HTTPS_PROXY environment variable to http://177.94.225.58:55674 (it should work a little slower than regular performance, but sometimes we got timeouts since it's a free proxy on Brazil).

In order to test that we are actually using the proxy variable, you can also use http://198.22.162.41:8080 which will generate a virtual device to return a forbidden page if running a bst test simple script.

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.58
