### ISSUE TITLE
Transform multi-file Jest stare output into a single file

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bst#622]
**Is your feature request related to a problem? Please describe.**
For our users, it's useful to have a single file report from our test runs that can be passed around via email.

**Describe the solution you'd like**
There are a variety of tools available to transform multiple file HTML/JS/CSS projects into a single, minified file.

The most popular one is webpack. We should add this to jest stare, configurable via the option `JEST_STARE_INLINE_SOURCE` (defaults to false).

I believe the best way to accomplish this is using Webpack with this plugin:
https://github.com/dustinjackson/html-webpack-inline-source-plugin

We can run this against the regular output created by Jest to create a single file report. The report should be named:
${JEST_STARE_RESULT_HTML} - `.html` + `.inline.html`

So if the RESULT_HTML is `bst_report.html`, the combined report will be:
`bst_report.inline.html`

**Describe alternatives you've considered**
There are other tools to do this such as:
https://github.com/fmal/gulp-inline-source/

That is based on gulp.

Another approach would be to just manually inline the specific files that are used. That should work as well.

I focused on the webpack approach because:
1) Webpack is popular
2) It allows for the inlined file to stay in sync easily with the template file (i.e., the inlined version is automatically kept up-to-date with the main html template)

**Comment by jkelvie** [comment]
We should take a look at this tool as an alternative to webpack:
https://parceljs.org

I think this actually looks like the most promising and easy-to-use.

**Comment by ecruzado** [comment]
https://github.com/bespoken/jest-stare/pull/6

**Comment by ecruzado** [comment]
I was testing generating the inline report using parcel API after the test is completed, I found some problems:

-  For some reason, jest is calling the method to generate the report more than once (3 times).
-  Bundling the files into a single file takes almost 10 seconds.
-  Parcel needs a testing.json file in the execution folder, and install some dependencies in order to run.

So I was wondering if it is correct to create a pre-bundled template with parcel and using it to generate the report. [This](https://github.com/bespoken/jest-stare/blob/master/web/template.html) is the template we are using right now. I can add a script to bundle the template before publishing the npm pakage. We can use the generated bundled template to generate the inline source report.

@jkelvie  Let me know what you think.

**Comment by ecruzado** [comment]
https://github.com/bespoken/jest-stare/pull/7

**Comment by ecruzado** [comment]
https://github.com/bespoken/bespoken-docs/pull/105

**Comment by MKen-li** [comment]
Marked as verified
Build = bespoken-tools@2.4.30
